version: '3.5'


services:
  postgres:
    container_name: postgres-pdi
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_pdi
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local